project_id = "kovspviddxhhlsekqlxa"

[functions.fetch-cnpj-data]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.get-os-report]
verify_jwt = false

[functions.reconcile-bank-statement]
verify_jwt = true
